// Command genbuiltins regenerates internal/catalog/builtins.tsv from the
// official Claude Code commands reference (decision D1, SPEC §5.2).
//
// Usage:
//
//	curl -sL https://code.claude.com/docs/en/commands.md -o /tmp/commands.md
//	go run ./tools/genbuiltins -in /tmp/commands.md -out internal/catalog/builtins.tsv
package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// | `/name <args>`   | {/* min-version: X */}description... |
var rowRE = regexp.MustCompile("^\\| `/([^`]+)` +\\| (.+?) +\\|$")

var (
	minVersionRE = regexp.MustCompile(`\{/\* min-version: ([0-9.]+) \*/\}`)
	annotationRE = regexp.MustCompile(`\{/\*[^}]*\*/\}`)
	linkRE       = regexp.MustCompile(`\[([^\]]*)\]\([^)]*\)`)
)

// row is one built-in command extracted from a docs table line.
type row struct {
	name       string
	minVersion string
	hint       string
	desc       string
}

// parseRow extracts a built-in command from one line of the docs markdown.
// Only table rows whose first cell is a backticked /command match; prose,
// headers, and the table's own header row return ok=false.
func parseRow(line string) (row, bool) {
	m := rowRE.FindStringSubmatch(line)
	if m == nil {
		return row{}, false
	}

	// First cell, e.g. "/advisor [model\|off]": unescape the pipes markdown
	// requires inside table cells, then split name from argument hint.
	nameCell := strings.ReplaceAll(m[1], `\|`, "|")
	name, hint, _ := strings.Cut(nameCell, " ")
	name = strings.TrimPrefix(name, "/")

	// Second cell: pull the first min-version annotation as the version
	// gate, then strip annotations and markdown down to plain prose. The
	// final whitespace collapse also guarantees a tab can never corrupt
	// the TSV.
	desc := m[2]
	minVersion := ""
	if v := minVersionRE.FindStringSubmatch(desc); v != nil {
		minVersion = v[1]
	}
	desc = annotationRE.ReplaceAllString(desc, "")
	desc = linkRE.ReplaceAllString(desc, "$1")
	desc = strings.ReplaceAll(desc, `\|`, "|")
	desc = strings.ReplaceAll(desc, "**", "")
	desc = strings.ReplaceAll(desc, "`", "")
	desc = strings.Join(strings.Fields(desc), " ")

	return row{name: name, minVersion: minVersion, hint: hint, desc: desc}, true
}

func (r row) tsv() string {
	return fmt.Sprintf("%s\t%s\t%s\t%s", r.name, r.minVersion, r.hint, r.desc)
}

// parseDoc extracts all command rows from the docs markdown, enforcing name
// uniqueness — a duplicate means the docs (or our parsing) changed in a way
// that must be looked at, never silently shipped.
func parseDoc(src string) ([]row, error) {
	var rows []row
	seen := map[string]bool{}
	for _, line := range strings.Split(src, "\n") {
		r, ok := parseRow(line)
		if !ok {
			continue
		}
		if seen[r.name] {
			return nil, fmt.Errorf("duplicate command %q in docs table", r.name)
		}
		seen[r.name] = true
		rows = append(rows, r)
	}
	if len(rows) == 0 {
		return nil, fmt.Errorf("no command rows matched — docs format changed?")
	}
	return rows, nil
}

func main() {
	in := flag.String("in", "", "path to commands.md (docs markdown)")
	out := flag.String("out", "internal/catalog/builtins.tsv", "output TSV path")
	flag.Parse()
	if *in == "" {
		fmt.Fprintln(os.Stderr, "genbuiltins: -in is required")
		os.Exit(2)
	}

	src, err := os.ReadFile(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genbuiltins:", err)
		os.Exit(1)
	}
	rows, err := parseDoc(string(src))
	if err != nil {
		fmt.Fprintln(os.Stderr, "genbuiltins:", err)
		os.Exit(1)
	}

	lines := make([]string, 0, len(rows))
	for _, r := range rows {
		lines = append(lines, r.tsv())
	}
	sort.Strings(lines)

	header := "# Generated by tools/genbuiltins from code.claude.com/docs/en/commands.md — do not edit.\n" +
		"# Columns: name, min_version, argument_hint, description\n"
	if err := os.WriteFile(*out, []byte(header+strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genbuiltins:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "genbuiltins: wrote %d commands to %s\n", len(rows), *out)
}
