// Command genbuiltins regenerates internal/catalog/builtins.tsv from the
// official Claude Code commands reference (decision D1, SPEC §5.2).
//
// Usage:
//
//	curl -sL https://code.claude.com/docs/en/commands.md -o /tmp/commands.md
//	go run ./tools/genbuiltins -in /tmp/commands.md -out internal/catalog/builtins.tsv
package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// | `/name <args>`   | {/* min-version: X */}description... |
var rowRE = regexp.MustCompile("^\\| `/([^`]+)` +\\| (.+?) +\\|$")

var (
	minVersionRE = regexp.MustCompile(`\{/\* min-version: ([0-9.]+) \*/\}`)
	annotationRE = regexp.MustCompile(`\{/\*[^}]*\*/\}`)
	linkRE       = regexp.MustCompile(`\[([^\]]*)\]\([^)]*\)`)
)

func main() {
	in := flag.String("in", "", "path to commands.md (docs markdown)")
	out := flag.String("out", "internal/catalog/builtins.tsv", "output TSV path")
	flag.Parse()
	if *in == "" {
		fmt.Fprintln(os.Stderr, "genbuiltins: -in is required")
		os.Exit(2)
	}

	src, err := os.ReadFile(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genbuiltins:", err)
		os.Exit(1)
	}

	var rows []string
	for _, line := range strings.Split(string(src), "\n") {
		m := rowRE.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		nameCell := strings.ReplaceAll(m[1], `\|`, "|")
		name, hint, _ := strings.Cut(nameCell, " ")
		name = strings.TrimPrefix(name, "/")

		desc := m[2]
		minVersion := ""
		if v := minVersionRE.FindStringSubmatch(desc); v != nil {
			minVersion = v[1]
		}
		desc = annotationRE.ReplaceAllString(desc, "")
		desc = linkRE.ReplaceAllString(desc, "$1")
		desc = strings.ReplaceAll(desc, `\|`, "|")
		desc = strings.ReplaceAll(desc, "**", "")
		desc = strings.ReplaceAll(desc, "`", "")
		desc = strings.Join(strings.Fields(desc), " ") // collapse whitespace, no tabs

		rows = append(rows, fmt.Sprintf("%s\t%s\t%s\t%s", name, minVersion, hint, desc))
	}
	if len(rows) == 0 {
		fmt.Fprintln(os.Stderr, "genbuiltins: no command rows matched — docs format changed?")
		os.Exit(1)
	}
	sort.Strings(rows)

	header := "# Generated by tools/genbuiltins from code.claude.com/docs/en/commands.md — do not edit.\n" +
		"# Columns: name, min_version, argument_hint, description\n"
	if err := os.WriteFile(*out, []byte(header+strings.Join(rows, "\n")+"\n"), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genbuiltins:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "genbuiltins: wrote %d commands to %s\n", len(rows), *out)
}
